using DbManager.Parser;
using System;


namespace DbManager
{
    public class ColumnDefinition
    {
        public enum DataType { String, Int, Double}

        public DataType Type;
        public string Name { get; private set; }


        public ColumnDefinition(DataType type, string name)
        {
            //TODO DEADLINE 1.A: Initialize member variables
            
        }

        private const string Delimiter = "->";
        private const string DelimiterEncoded = "[ARROW]";

        private static string Encode(string value)
        {
            //TODO DEADLINE 1.C: Encode the delimiter in the value
            
            return null;
            
        }

        private static string Decode(string value)
        {
            //TODO DEADLINE 1.C: Decode the delimiter in the value
            
            return null;
            
        }

        public string AsText()
        {
            //TODO DEADLINE 1.C: Return the column as a string with the name and the type separated by the delimiter
            
            return null;
            
        }

        public static ColumnDefinition Parse(string value)
        {
            //TODO DEADLINE 1.C: Parse the column's name and type from a string generated by AsText()
            
            return null;
            
        }
    }
}
